### ISSUE TITLE
doesn't even start

### ISSUE THREAD

**Issue by EnvyRunsU** [misutesu-desu/MudaRemote#37]
Microsoft Windows [Version 10.0.19045.6036]
(c) Microsoft Corporation. All rights reserved.

C:\Users\victo\Downloads\MudaRemote-main(1)\MudaRemote-main>python mudae_bot.py
Traceback (most recent call last):
  File "C:\Users\victo\Downloads\MudaRemote-main(1)\MudaRemote-main\mudae_bot.py", line 3, in <module>
    import discord
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\__init__.py", line 22, in <module>
    from . import abc as abc, opus as opus, utils as utils
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\abc.py", line 58, in <module>
    from .http import handle_message_parameters
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 53, in <module>
    import aiohttp
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import (
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 170, in <module>
    class _RequestOptions(TypedDict, total=False):
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 196, in _RequestOptions
    middlewares: Optional[Sequence[ClientMiddlewareType]]
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\typing.py", line 243, in inner
    return func(*args, **kwds)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\typing.py", line 433, in Optional
    return Union[arg, type(None)]
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\typing.py", line 243, in inner
    return func(*args, **kwds)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\typing.py", line 421, in Union
    parameters = _remove_dups_flatten(parameters)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\typing.py", line 694, in __hash__
    return hash((self.__origin__, self.__args__))
TypeError: unhashable type: 'list'

C:\Users\victo\Downloads\MudaRemote-main(1)\MudaRemote-main>
getting this issue

**Comment by EnvyRunsU** [comment]
Microsoft Windows [Version 10.0.19045.6036]
(c) Microsoft Corporation. All rights reserved.

C:\Users\victo\Downloads\MudaRemote-main(1)\MudaRemote-main>python mudae_bot.py
Traceback (most recent call last):
  File "C:\Users\victo\Downloads\MudaRemote-main(1)\MudaRemote-main\mudae_bot.py", line 3, in <module>
    import discord
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\__init__.py", line 22, in <module>
    from . import abc as abc, opus as opus, utils as utils
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\abc.py", line 58, in <module>
    from .http import handle_message_parameters
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 53, in <module>
    import aiohttp
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import (
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 170, in <module>
    class _RequestOptions(TypedDict, total=False):
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 196, in _RequestOptions
    middlewares: Optional[Sequence[ClientMiddlewareType]]
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\typing.py", line 243, in inner
    return func(*args, **kwds)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\typing.py", line 433, in Optional
    return Union[arg, type(None)]
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\typing.py", line 243, in inner
    return func(*args, **kwds)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\typing.py", line 421, in Union
    parameters = _remove_dups_flatten(parameters)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python39\lib\typing.py", line 694, in __hash__
    return hash((self.__origin__, self.__args__))
TypeError: unhashable type: 'list'

C:\Users\victo\Downloads\MudaRemote-main(1)\MudaRemote-main>
getting this now

**Comment by misutesu-desu** [comment]
Which version of python are you using?

**Comment by EnvyRunsU** [comment]
fixed it by clearing python 3.9 and 10 in files then getting the microsoft store one

**Comment by EnvyRunsU** [comment]
[2025-06-29 14:49:06] [INFO    ] discord.http: Found user agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36, build number 414005.
[2025-06-29 14:49:07][Preset_3_Casual_Roller] [MudaRemote] LoginFail 'Preset_3_Casual_Roller'. Check token.
[2025-06-29 14:49:07][Preset_3_Casual_Roller] Bot instance for 'Preset_3_Casual_Roller' has stopped. Restarting in 60 seconds...
nvmmm getting a second issue

**Comment by misutesu-desu** [comment]
Make sure you have written your token correctly in your presets.json file

**Comment by BellaDona007** [comment]
It doesn't start here either. I tried it once in the past and got the same error. I tried installing another version, without success. I went back to the latest version and even after running the commands shown, the problem persists.

<img width="1007" height="537" alt="Image" src="https://github.com/user-attachments/assets/b8965063-a87e-4393-af3c-0d77e454d374" />

**Comment by BellaDona007** [comment]
I managed to solve the problem after installing this version https://www.python.org/downloads/release/python-3110/
